### Scrapping thông tin Restaurant

In [160]:
import os

directory = 'Scrapping data/'

Restaurant = []

for filename in os.listdir(directory):
    if filename.endswith('.txt') and filename != 'Restaurant Info.txt':  
        Restaurant.append(filename) 

# Print the list of file names
print(Restaurant)

['Lò Quay Sài Gòn -   Cách Mạng Tháng 8.txt', 'NEM NƯỚNG THANH THẢO - Nem Nướng & Bún Thịt Nướng - 67 D1.txt', 'Quán Ăn Minh Ký - Ẩm Thực Việt Hoa - Đại Lộ Bình Dương.txt']

In [161]:
with open('Scrapping data/Restaurant Info.txt', 'r', encoding='utf-8') as file:
    restaurant_info = file.readlines()  # Read all lines into a list
restaurant_info

['Lò Quay Sài Gòn -   Cách Mạng Tháng 8\n',
 'Address: 50/2 Cách Mạng Tháng 8, P. An Thạnh , Thị Xã Thuận An , Bình Dương.\n',
 'Time: 05:00 - 23:30\n',
 'Price: 130.000đ - 1.100.000 VND\n',
 'NEM NƯỚNG THANH THẢO - Nem Nướng & Bún Thịt Nướng - 67 D1\n',
 'Address: 67 Đường D1 Khu Dân Cư Phú Hoà, P. Phú Hòa, Thị xã Thủ Dầu Một, Bình Dương\n',
 'Time: 06:30 - 22:00\n',
 'Price: 0 - 0 VND\n',
 'Quán Ăn Minh Ký - Ẩm Thực Việt Hoa - Đại Lộ Bình Dương\n',
 'Address: 492 Đường D1, P. Phú Hòa, Thành Phố Thủ Dầu Một, Bình Dương\n',
 'Time: 09:00 - 22:00\n',
 'Price: 40000 - 70000 VND']

In [162]:
restaurant_names = []
addresses = []
operating_times = []
prices = []

for i in range(0, len(restaurant_info), 4):
    restaurant_names.append(restaurant_info[i].strip())

for i in range(1, len(restaurant_info), 4):
    addresses.append(restaurant_info[i].strip().replace('Address: ', ''))

for i in range(2, len(restaurant_info), 4):
    operating_times.append(restaurant_info[i].strip().replace('Time: ', ''))

for i in range(3, len(restaurant_info), 4):
    price = restaurant_info[i].strip().replace('Price: ', '').replace(' VND', '')  # Corrected line
    prices.append(price)
print("Restaurant Names:", restaurant_names)
print("Addresses:", addresses)
print("Operating Times:", operating_times)
print("Prices:", prices)

Restaurant Names: ['Lò Quay Sài Gòn -   Cách Mạng Tháng 8', 'NEM NƯỚNG THANH THẢO - Nem Nướng & Bún Thịt Nướng - 67 D1', 'Quán Ăn Minh Ký - Ẩm Thực Việt Hoa - Đại Lộ Bình Dương']
Addresses: ['50/2 Cách Mạng Tháng 8, P. An Thạnh , Thị Xã Thuận An , Bình Dương.', '67 Đường D1 Khu Dân Cư Phú Hoà, P. Phú Hòa, Thị xã Thủ Dầu Một, Bình Dương', '492 Đường D1, P. Phú Hòa, Thành Phố Thủ Dầu Một, Bình Dương']
Operating Times: ['05:00 - 23:30', '06:30 - 22:00', '09:00 - 22:00']
Prices: ['130.000đ - 1.100.000', '0 - 0', '40000 - 70000']

In [163]:
import pandas as pd

data = {
    'ID': range(1623, 1623 + len(restaurant_names)),
    'Restaurant': restaurant_names,
    'Address': addresses,
    'Time': operating_times,
    'Price': prices
}

df = pd.DataFrame(data)

df

,ID,Restaurant,Address,Time,Price
0,1623,Lò Quay Sài Gòn - Cách Mạng Tháng 8,"50/2 Cách Mạng Tháng 8, P. An Thạnh , Thị Xã T...",05:00 - 23:30,130.000đ - 1.100.000
1,1624,NEM NƯỚNG THANH THẢO - Nem Nướng & Bún Thịt Nư...,"67 Đường D1 Khu Dân Cư Phú Hoà, P. Phú Hòa, Th...",06:30 - 22:00,0 - 0
2,1625,Quán Ăn Minh Ký - Ẩm Thực Việt Hoa - Đại Lộ Bì...,"492 Đường D1, P. Phú Hòa, Thành Phố Thủ Dầu Mộ...",09:00 - 22:00,40000 - 70000

In [164]:
df.loc[df['Restaurant'] == "Lò Quay Sài Gòn -   Cách Mạng Tháng 8", 'ID'].values[0]

1623

In [165]:
df

,ID,Restaurant,Address,Time,Price
0,1623,Lò Quay Sài Gòn - Cách Mạng Tháng 8,"50/2 Cách Mạng Tháng 8, P. An Thạnh , Thị Xã T...",05:00 - 23:30,130.000đ - 1.100.000
1,1624,NEM NƯỚNG THANH THẢO - Nem Nướng & Bún Thịt Nư...,"67 Đường D1 Khu Dân Cư Phú Hoà, P. Phú Hòa, Th...",06:30 - 22:00,0 - 0
2,1625,Quán Ăn Minh Ký - Ẩm Thực Việt Hoa - Đại Lộ Bì...,"492 Đường D1, P. Phú Hòa, Thành Phố Thủ Dầu Mộ...",09:00 - 22:00,40000 - 70000

In [166]:
df.to_csv('Restaurant_scrapping.csv', index=False)

### Scrapping thông tin Review cho từng Restaurant

In [167]:
for filename in Restaurant:
    print(filename)

Lò Quay Sài Gòn -   Cách Mạng Tháng 8.txt
NEM NƯỚNG THANH THẢO - Nem Nướng & Bún Thịt Nướng - 67 D1.txt
Quán Ăn Minh Ký - Ẩm Thực Việt Hoa - Đại Lộ Bình Dương.txt

In [168]:
import re

name = []
rating = []
reviews = []
id_restaurant = []
time = []
for filename in Restaurant:
    with open(os.path.join(directory, filename), 'r', encoding='utf-8') as file:
        lines = file.readlines()
    data_without_newline = [item.replace('\n', '') for item in lines]
    # Define a regular expression pattern to match date and time strings
    date_time_pattern = r'\d{2}-\d{2}-\d{4} \d{2}:\d{2}'

    # Extract all date and time strings from the list
    date_times = re.findall(date_time_pattern, ' '.join(data_without_newline))
    time.extend(date_times)
    result = []
    sublist = []

    for item in data_without_newline:
        sublist.append(item)
        if item in date_times:
            result.append(sublist)
            sublist = []
            list_2 = date_times[date_times.index(item):]
    if sublist:  
        result.append(sublist)
    for sublist in result:
        name.append(sublist[0])
        rating.append(sublist[1])
        reviews.append(' '.join(sublist[2:-1]))
        id_restaurant.append(df.loc[df['Restaurant'] == filename.replace(".txt",""), 'ID'].values[0])

In [169]:
time

['28-02-2024 18:22',
 '21-01-2024 12:05',
 '17-01-2024 21:20',
 '06-01-2024 01:31',
 '31-12-2023 05:26',
 '12-12-2023 19:21',
 '28-11-2023 15:21',
 '15-11-2023 13:56',
 '14-10-2023 11:57',
 '25-09-2023 23:35',
 '19-09-2023 20:37',
 '13-09-2023 20:25',
 '28-08-2023 01:24',
 '14-08-2023 12:46',
 '05-08-2023 09:49',
 '23-07-2023 16:07',
 '19-07-2023 15:28',
 '15-07-2023 12:39',
 '03-06-2023 21:02',
 '17-04-2023 14:14',
 '13-04-2023 11:11',
 '05-03-2023 11:31',
 '28-02-2023 20:01',
 '19-02-2023 15:20',
 '19-02-2023 11:57',
 '09-02-2023 18:31',
 '25-01-2023 12:41',
 '08-01-2023 17:02',
 '02-01-2023 21:02',
 '29-12-2022 19:08',
 '27-12-2022 08:07',
 '25-12-2022 10:55',
 '16-12-2022 12:43',
 '28-11-2022 17:55',
 '27-11-2022 11:47',
 '13-11-2022 18:05',
 '11-11-2022 20:43',
 '06-11-2022 20:25',
 '30-10-2022 13:10',
 '14-10-2022 17:36',
 '09-10-2022 17:58',
 '07-10-2022 11:56',
 '01-10-2022 17:14',
 '27-09-2022 10:42',
 '24-09-2022 00:10',
 '06-09-2022 20:57',
 '04-09-2022 14:19',
 '24-08-2022 12:22',
 '26-07-2022 17:23',
 '06-06-2022 18:49',
 '12-04-2022 14:43',
 '16-03-2022 19:56',
 '12-03-2022 15:31',
 '26-02-2022 20:24',
 '20-02-2022 20:31',
 '12-03-2022 15:31',
 '26-02-2022 20:24',
 '20-02-2022 20:31',
 '22-01-2022 19:56',
 '16-01-2022 12:48',
 '26-12-2021 17:44',
 '21-12-2021 13:38',
 '11-12-2021 20:23',
 '11-12-2021 13:17',
 '08-12-2021 17:40',
 '05-12-2021 15:14',
 '04-12-2021 07:54',
 '30-11-2021 11:08',
 '26-11-2021 17:40',
 '19-11-2021 16:47',
 '17-11-2021 12:39',
 '07-11-2021 18:02',
 '18-10-2021 18:49',
 '11-10-2021 12:05',
 '10-10-2021 17:13',
 '06-10-2021 16:27',
 '05-10-2021 18:42',
 '04-10-2021 10:13',
 '03-10-2021 11:27',
 '29-09-2021 18:54',
 '21-09-2021 16:03',
 '21-09-2021 10:15',
 '06-08-2021 21:19',
 '29-07-2021 14:51',
 '22-07-2021 15:10',
 '22-07-2021 14:51',
 '17-07-2021 16:46',
 '13-07-2021 18:19',
 '10-07-2021 06:49',
 '30-06-2021 21:04',
 '25-02-2020 19:47',
 '25-12-2019 10:54',
 '24-12-2019 21:04',
 '17-12-2019 20:18',
 '09-12-2019 18:03',
 '09-12-2019 07:38',
 '04-12-2019 13:45',
 '29-11-2019 15:56',
 '09-03-2024 13:18',
 '09-03-2024 11:44',
 '08-03-2024 16:48',
 '07-03-2024 12:17',
 '04-03-2024 17:24',
 '04-03-2024 10:19',
 '03-03-2024 13:01',
 '29-02-2024 11:54',
 '27-02-2024 19:29',
 '26-02-2024 18:05',
 '25-02-2024 13:47',
 '24-02-2024 16:12',
 '24-02-2024 09:49',
 '23-02-2024 22:07',
 '22-02-2024 11:53',
 '20-02-2024 09:20',
 '06-02-2024 13:11',
 '05-02-2024 11:43',
 '04-02-2024 10:24',
 '03-02-2024 11:52',
 '02-02-2024 00:04',
 '31-01-2024 21:59',
 '28-01-2024 13:35',
 '28-01-2024 10:40',
 '26-01-2024 21:52',
 '24-01-2024 10:19',
 '23-01-2024 13:15',
 '23-01-2024 12:44',
 '20-01-2024 12:27',
 '17-01-2024 09:46',
 '15-01-2024 20:06',
 '15-01-2024 16:29',
 '14-01-2024 20:30',
 '14-01-2024 19:39',
 '14-01-2024 19:30',
 '14-01-2024 12:28',
 '13-01-2024 08:52',
 '10-01-2024 11:34',
 '09-01-2024 21:30',
 '09-01-2024 08:50',
 '06-01-2024 14:06',
 '04-01-2024 17:01',
 '01-01-2024 20:11',
 '31-12-2023 14:23',
 '30-12-2023 08:48',
 '27-12-2023 17:51',
 '27-12-2023 14:31',
 '26-12-2023 12:59',
 '26-12-2023 00:50',
 '17-11-2023 18:27',
 '17-11-2023 09:37',
 '15-11-2023 13:18',
 '14-11-2023 12:02',
 '14-11-2023 11:53',
 '11-11-2023 11:08',
 '11-11-2023 09:36',
 '10-11-2023 14:19',
 '10-11-2023 11:28',
 '09-11-2023 12:04',
 '07-11-2023 16:08',
 '07-11-2023 12:35',
 '07-11-2023 09:59',
 '05-11-2023 20:16',
 '05-11-2023 19:15',
 '05-11-2023 11:06',
 '03-11-2023 11:31',
 '31-10-2023 19:23',
 '31-10-2023 11:58',
 '29-10-2023 09:59',
 '27-10-2023 14:41',
 '24-10-2023 18:04',
 '24-10-2023 11:20',
 '23-10-2023 18:19',
 '18-10-2023 20:39',
 '26-12-2023 12:59',
 '26-12-2023 00:50',
 '25-12-2023 13:33',
 '25-12-2023 08:00',
 '23-12-2023 15:13',
 '17-12-2023 11:14',
 '15-12-2023 11:42',
 '15-12-2023 11:06',
 '13-12-2023 11:54',
 '12-12-2023 19:03',
 '12-12-2023 13:20',
 '09-12-2023 15:13',
 '07-12-2023 22:03',
 '07-12-2023 13:05',
 '06-12-2023 12:45',
 '04-12-2023 12:03',
 '04-12-2023 07:49',
 '01-12-2023 11:57',
 '30-11-2023 08:47',
 '28-11-2023 10:57',
 '27-11-2023 12:29',
 '21-11-2023 14:30',
 '21-11-2023 10:06',
 '17-11-2023 18:27',
 '17-11-2023 09:37',
 '24-10-2023 11:20',
 '23-10-2023 18:19',
 '18-10-2023 20:39',
 '18-10-2023 13:24',
 '18-10-2023 12:13',
 '15-10-2023 19:09',
 '15-10-2023 09:51',
 '14-10-2023 10:55',
 '13-10-2023 11:18',
 '12-10-2023 19:07',
 '12-10-2023 12:23',
 '12-10-2023 10:43',
 '11-10-2023 09:26',
 '09-10-2023 12:10',
 '30-09-2023 11:40',
 '29-09-2023 11:10',
 '28-09-2023 11:05',
 '27-09-2023 12:37',
 '23-09-2023 12:00',
 '20-09-2023 15:19',
 '16-09-2023 12:54',
 '15-09-2023 12:20',
 '14-09-2023 17:44',
 '13-09-2023 09:53',
 '12-09-2023 13:30',
 '11-09-2023 11:25',
 '11-09-2023 11:04',
 '05-09-2023 09:56',
 '23-10-2023 18:19',
 '18-10-2023 20:39',
 '18-10-2023 13:24',
 '18-10-2023 12:13',
 '15-10-2023 19:09',
 '15-10-2023 09:51',
 '14-10-2023 10:55',
 '13-10-2023 11:18',
 '12-10-2023 19:07',
 '12-10-2023 12:23',
 '12-10-2023 10:43',
 '11-10-2023 09:26',
 '09-10-2023 12:10',
 '30-09-2023 11:40',
 '29-09-2023 11:10',
 '28-09-2023 11:05',
 '27-09-2023 12:37',
 '23-09-2023 12:00',
 '20-09-2023 15:19',
 '16-09-2023 12:54',
 '15-09-2023 12:20',
 '14-09-2023 17:44',
 '13-09-2023 09:53',
 '12-09-2023 13:30',
 '11-09-2023 11:25',
 '11-09-2023 11:04',
 '05-09-2023 09:56',
 '14-05-2023 12:25',
 '13-05-2023 19:38',
 '13-05-2023 17:50',
 '13-05-2023 11:40',
 '11-05-2023 19:50',
 '11-05-2023 12:36',
 '11-05-2023 10:19',
 '11-05-2023 07:14',
 '09-05-2023 12:21',
 '06-05-2023 11:44',
 '06-05-2023 11:29',
 '16-03-2023 23:08',
 '15-03-2023 10:40',
 '14-03-2023 15:56',
 '14-03-2023 12:31',
 '13-03-2023 08:46',
 '11-03-2023 01:09',
 '10-03-2023 17:37',
 '10-03-2023 13:05',
 '06-03-2023 05:57',
 '04-03-2023 18:54',
 '03-03-2023 17:02',
 '02-03-2023 17:52',
 '01-03-2023 21:47',
 '05-10-2022 16:16',
 '05-10-2022 10:14',
 '04-10-2022 12:15',
 '04-10-2022 12:10',
 '04-10-2022 08:54',
 '02-10-2022 13:08',
 '02-10-2022 12:43',
 '29-09-2022 19:54',
 '29-09-2022 10:00',
 '29-09-2022 13:43',
 '28-09-2022 15:33',
 '28-09-2022 13:50',
 '27-09-2022 11:19',
 '25-09-2022 23:57',
 '25-09-2022 19:06',
 '24-09-2022 19:08',
 '22-09-2022 14:02',
 '22-09-2022 10:22',
 '20-09-2022 18:28',
 '19-09-2022 19:58',
 '18-09-2022 20:29',
 '18-09-2022 07:58',
 '14-09-2022 13:14',
 '14-09-2022 11:52',
 '10-09-2022 13:14',
 '03-03-2023 17:02',
 '02-03-2023 17:52',
 '01-03-2023 21:47',
 '01-03-2023 11:03',
 '28-02-2023 18:18',
 '27-02-2023 10:32',
 '24-02-2023 13:35',
 '23-02-2023 12:34',
 '22-02-2023 18:17',
 '22-02-2023 13:22',
 '22-02-2023 11:54',
 '22-02-2023 11:49',
 '22-02-2023 09:05',
 '21-02-2023 19:44',
 '21-02-2023 19:35',
 '21-02-2023 13:42',
 '21-02-2023 10:58',
 '20-02-2023 19:48',
 '20-02-2023 12:56',
 '19-02-2023 18:31',
 '08-10-2022 10:30',
 '07-10-2022 21:14',
 '07-10-2022 13:23',
 '07-10-2022 13:07',
 '06-10-2022 16:21',
 '06-10-2022 09:51',
 '05-10-2022 16:16',
 '05-10-2022 16:16',
 '11-09-2023 11:04',
 '05-09-2023 09:56',
 '01-09-2023 12:29',
 '31-08-2023 11:12',
 '30-08-2023 18:53',
 '26-08-2023 22:59',
 '25-08-2023 12:07',
 '24-08-2023 11:33',
 '23-08-2023 10:54',
 '22-08-2023 21:11',
 '20-08-2023 11:45',
 '16-08-2023 11:46',
 '15-08-2023 23:15',
 '14-08-2023 12:07',
 '13-08-2023 14:00',
 '13-08-2023 14:00',
 '12-08-2023 13:32',
 '11-08-2023 15:06',
 '11-08-2023 13:40',
 '11-08-2023 09:50',
 '10-08-2023 16:28',
 '10-08-2023 11:19',
 '08-08-2023 15:54',
 '07-08-2023 11:26',
 '05-08-2023 11:17',
 '04-08-2023 14:00',
 '04-08-2023 09:59',
 '03-08-2023 17:11',
 '08-07-2023 20:41',
 '08-07-2023 12:26',
 '06-07-2023 14:29',
 '03-07-2023 11:40',
 '02-07-2023 14:33',
 '01-07-2023 11:53',
 '30-06-2023 13:43',
 '30-06-2023 11:38',
 '26-06-2023 10:58',
 '22-05-2023 20:47',
 '22-05-2023 11:35',
 '22-05-2023 10:38',
 '22-05-2023 06:16',
 '20-05-2023 17:55',
 '20-05-2023 14:40',
 '18-05-2023 12:53',
 '18-05-2023 11:10',
 '18-05-2023 09:38',
 '17-05-2023 15:06',
 '16-05-2023 23:50',
 '16-05-2023 14:15',
 '15-05-2023 17:42',
 '15-05-2023 13:50',
 '15-05-2023 11:05',
 '14-05-2023 12:25',
 '13-05-2023 19:38',
 '13-05-2023 19:37',
 '22-10-2023 10:40',
 '18-10-2023 18:18',
 '18-10-2023 17:37',
 '17-10-2023 21:34',
 '08-10-2023 18:46',
 '04-10-2023 20:38',
 '04-10-2023 16:11',
 '01-10-2023 19:38',
 '30-09-2023 16:26',
 '28-09-2023 11:46',
 '21-09-2023 20:31',
 '18-09-2023 22:36',
 '17-09-2023 12:26',
 '27-06-2023 11:50',
 '25-06-2023 23:14',
 '23-06-2023 09:38',
 '22-06-2023 11:08',
 '20-06-2023 19:57',
 '20-06-2023 18:38',
 '18-06-2023 20:18',
 '05-06-2023 19:29',
 '04-06-2023 08:29',
 '02-06-2023 21:07',
 '02-06-2023 19:29',
 '30-05-2023 17:35',
 '28-05-2023 12:02',
 '10-03-2024 18:08',
 '09-03-2024 21:23',
 '09-03-2024 21:20',
 '06-03-2024 15:44',
 '03-03-2024 17:20',
 '02-03-2024 14:01',
 '27-02-2024 11:43',
 '27-02-2024 11:42',
 '23-02-2024 13:50',
 '19-02-2024 13:06',
 '18-02-2024 14:27',
 '17-02-2024 13:23',
 '15-02-2024 14:07',
 '15-02-2024 14:07',
 '01-02-2024 11:30',
 '01-02-2024 11:08',
 '26-01-2024 19:50',
 '24-01-2024 19:48',
 '23-01-2024 14:52',
 '21-01-2024 06:32',
 '19-01-2024 20:25',
 '14-01-2024 20:05',
 '14-01-2024 19:37',
 '19-01-2024 20:25',
 '14-01-2024 20:05',
 '14-01-2024 19:37',
 '10-01-2024 12:42',
 '10-01-2024 09:15',
 '08-01-2024 20:59',
 '05-01-2024 22:30',
 '02-01-2024 14:45',
 '28-12-2023 21:36',
 '28-12-2023 13:47',
 '11-12-2023 18:11',
 '28-11-2023 18:03',
 '25-11-2023 12:59',
 '25-11-2023 12:54',
 '22-11-2023 14:40',
 '22-11-2023 13:26',
 '03-11-2023 20:30',
 '03-11-2023 15:34',
 '02-11-2023 19:00',
 '02-11-2023 14:57',
 '31-10-2023 20:50',
 '29-10-2023 20:28',
 '23-10-2023 23:37',
 '22-10-2023 11:20',
 '22-10-2023 10:40',
 '02-06-2023 19:29',
 '30-05-2023 17:35',
 '28-05-2023 12:02',
 '27-05-2023 23:02',
 '24-05-2023 17:44',
 '24-05-2023 11:47',
 '18-05-2023 11:47',
 '16-05-2023 11:44',
 '16-05-2023 10:46',
 '13-05-2023 11:45',
 '11-05-2023 18:41',
 '09-05-2023 17:52',
 '09-05-2023 11:49',
 '09-05-2023 08:25',
 '08-05-2023 13:37',
 '07-05-2023 21:27',
 '07-05-2023 21:25',
 '07-05-2023 20:53',
 '07-05-2023 13:19',
 '06-05-2023 10:28',
 '10-07-2022 14:58',
 '09-07-2022 12:29',
 '07-07-2022 23:13',
 '07-07-2022 23:12',
 '06-07-2022 17:13',
 '03-07-2022 12:02',
 '02-07-2022 17:23',
 '29-06-2022 15:56',
 '29-06-2022 15:56',
 '02-07-2022 17:23',
 '29-06-2022 15:56',
 '26-06-2022 14:40',
 '18-06-2022 11:13',
 '09-06-2022 15:14',
 '09-06-2022 08:57',
 '06-06-2022 19:51',
 '05-06-2022 23:39',
 '03-06-2022 18:16',
 '02-06-2022 19:00',
 '01-06-2022 21:26',
 '15-05-2022 12:51',
 '14-05-2022 11:55',
 '13-05-2022 15:30',
 '12-05-2022 14:42',
 '11-05-2022 19:15',
 '11-05-2022 17:19',
 '11-05-2022 16:20',
 '07-05-2022 14:50',
 '07-05-2022 13:45',
 '01-05-2022 15:04',
 '29-04-2022 19:17',
 '28-04-2022 22:03',
 '26-04-2022 10:23',
 '23-04-2022 11:47',
 '21-04-2022 21:46',
 '21-04-2022 13:33',
 '20-04-2022 13:17',
 '19-04-2022 17:30',
 '20-04-2022 13:17',
 '19-04-2022 17:30',
 '17-04-2022 16:46',
 '15-04-2022 13:18',
 '12-04-2022 06:22',
 '06-04-2022 12:22',
 '06-04-2022 11:59',
 '03-04-2022 19:46',
 '03-04-2022 01:26',
 '03-04-2022 01:24',
 '02-04-2022 12:05',
 '30-03-2022 12:21',
 '25-03-2022 20:29',
 '20-03-2022 17:22',
 '20-03-2022 15:41',
 '18-03-2022 11:50',
 '16-03-2022 20:11',
 '14-03-2022 13:32',
 '10-03-2022 23:42',
 '08-03-2022 12:12',
 '07-03-2022 18:21',
 '05-03-2022 18:55',
 '04-03-2022 15:08',
 '04-03-2022 08:21',
 '03-03-2022 08:11',
 '04-03-2022 08:21',
 '03-03-2022 08:11',
 '02-03-2022 23:55',
 '02-03-2022 23:54',
 '02-03-2022 23:52',
 '28-02-2022 09:25',
 '27-02-2022 21:58',
 '26-02-2022 11:51',
 '23-02-2022 11:17',
 '17-02-2022 13:09',
 '16-02-2022 17:36',
 '11-02-2022 11:41',
 '08-02-2022 21:35',
 '08-02-2022 19:09',
 '07-02-2022 21:04',
 '03-02-2022 21:07',
 '01-02-2022 10:06',
 '31-01-2022 21:37',
 '28-01-2022 11:27',
 '26-01-2022 23:36',
 '25-01-2022 23:29',
 '25-01-2022 10:04',
 '24-01-2022 09:41',
 '23-01-2022 20:12',
 '23-01-2022 20:11',
 '01-03-2021 15:24',
 '23-02-2021 14:58',
 '16-02-2021 19:10',
 '16-02-2021 15:07',
 '13-02-2021 12:18',
 '06-02-2021 14:06',
 '06-02-2021 13:43',
 '06-02-2021 03:08',
 '03-02-2021 14:39',
 '02-02-2021 10:50',
 '29-01-2021 19:07',
 '28-01-2021 12:04',
 '26-01-2021 12:15',
 '24-01-2021 17:46',
 '19-01-2021 10:23',
 '17-10-2020 19:15',
 '13-10-2020 19:29',
 '07-10-2020 14:56',
 '05-09-2020 13:14',
 '28-08-2020 12:01',
 '26-07-2020 12:15',
 '18-07-2020 13:48',
 '07-07-2020 12:35',
 '03-06-2020 18:47',
 '30-05-2020 11:43',
 '27-05-2020 21:01',
 '21-05-2020 15:18',
 '14-05-2020 12:10',
 '25-04-2020 22:22',
 '19-04-2020 09:36',
 '17-04-2020 20:33',
 '09-04-2020 19:29',
 '23-01-2022 20:12',
 '23-01-2022 07:57',
 '22-01-2022 13:42',
 '21-01-2022 14:36',
 '20-01-2022 12:36',
 '19-01-2022 17:22',
 '18-01-2022 12:29',
 '16-01-2022 08:59',
 '12-01-2022 19:10',
 '12-01-2022 11:19',
 '11-05-2021 12:28',
 '04-05-2021 11:26',
 '02-05-2021 14:04',
 '29-04-2021 22:00',
 '22-04-2021 19:46',
 '20-04-2021 11:56',
 '09-04-2021 11:50',
 '06-04-2021 16:39',
 '04-04-2021 10:40',
 '31-03-2021 12:17',
 '30-03-2021 13:17',
 '30-03-2021 11:36',
 '29-03-2021 13:54',
 '14-03-2021 22:47',
 '12-03-2021 21:59',
 '01-03-2021 15:24',
 '23-02-2021 14:58',
 '21-02-2021 12:01']

In [178]:
data_review = {
    'ID': range(29960, 29960 + len(name) ),
    'User': name,
    'Time': time,
    'Rating': rating,
    'Comment': reviews,
    'IDRestaurant': id_restaurant
}

df_review = pd.DataFrame(data_review)

df_review

,ID,User,Time,Rating,Comment,IDRestaurant
0,29960,Loan Vỏ,28-02-2024 18:22,10,Do an ngon gia rẻ. Minh rất thích quan nay.se ...,1623
1,29961,tranthiet854ta,21-01-2024 12:05,10,Heo quay rất ngon...da giòn...cân đủ...giao hà...,1623
2,29962,Ẩn Danh,17-01-2024 21:20,10,"Giao hàng nhanh, đóng gói cẩn thận thịt nướng ...",1623
3,29963,baotran.74,06-01-2024 01:31,10,Hình ảnh mang tính chất nhận xu Đồ ăn ở đây ng...,1623
4,29964,K Vương Khang,31-12-2023 05:26,2,ít thịt toanf mỡ với da thôi,1623
...,...,...,...,...,...,...
621,30581,Ẩn Danh,14-03-2021 22:47,1,Có con sâu trong rau. Lần sau mong bếp rửa rau...,1625
622,30582,Ẩn Danh,12-03-2021 21:59,10,"Món ngon, sạch sẽ, giá tôtd. Hình ảnh mang tín...",1625
623,30583,Thùy Dung,01-03-2021 15:24,10,Đồ ăn ngon )))):):)):’djdkembdndkenendnxndjejj...,1625
624,30584,Ẩn Danh,23-02-2021 14:58,10,NG00000000000000000000NN? NNNNNNNNNNNNNNNNNNNN...,1625
625,30585,foodee_lgfl0dy8,21-02-2021 12:01,1,Quán quá mất dạy. Bán rất là đắt phần đặt biệt...,1625

In [179]:
df_review.to_csv('Review_scrapping.csv', index=False)